'use strict';

/**
 * Cross-platform "run at login" management — no admin rights required.
 *
 *   - Windows: a hidden-launch .vbs in the user's Startup folder.
 *   - macOS:   a LaunchAgent plist (loaded via launchctl).
 *   - Linux:   an XDG autostart .desktop entry.
 *
 * All of them simply launch `node <daemon.js>`. The daemon's own
 * single-instance lock ensures that even if autostart AND a manual start both
 * fire, only one helper actually runs.
 */

const fs = require('fs');
const os = require('os');
const path = require('path');
const { exec } = require('child_process');

const DAEMON = path.join(__dirname, 'daemon.js');
const NODE = process.execPath; // absolute path to the current node binary

// ── Path helpers ────────────────────────────────────────────────────────────
function windowsStartupVbs() {
  const appData = process.env.APPDATA || path.join(os.homedir(), 'AppData', 'Roaming');
  return path.join(
    appData, 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup',
    'claude-discord-presence.vbs'
  );
}
function macPlist() {
  return path.join(os.homedir(), 'Library', 'LaunchAgents', 'com.claude.discordpresence.plist');
}
function linuxDesktop() {
  const base = process.env.XDG_CONFIG_HOME || path.join(os.homedir(), '.config');
  return path.join(base, 'autostart', 'claude-discord-presence.desktop');
}

// ── Windows ───────────────────────────────────────────────────────────────────
function installWindows() {
  const vbsPath = windowsStartupVbs();
  fs.mkdirSync(path.dirname(vbsPath), { recursive: true });

  // The command we want to run, with each path quoted (handles spaces).
  const command = `"${NODE}" "${DAEMON}"`;
  // To embed that inside a VBS string literal, every " becomes "".
  const vbsArg = '"' + command.replace(/"/g, '""') + '"';
  const vbs = [
    "' Auto-generated by claude-discord-presence. Delete this file to disable autostart.",
    'Set WshShell = CreateObject("WScript.Shell")',
    `WshShell.Run ${vbsArg}, 0, False`, // window style 0 = hidden, async
    'Set WshShell = Nothing',
    '',
  ].join('\r\n');

  fs.writeFileSync(vbsPath, vbs);
  return Promise.resolve(vbsPath);
}
function uninstallWindows() {
  const p = windowsStartupVbs();
  if (fs.existsSync(p)) fs.unlinkSync(p);
  return Promise.resolve(p);
}

// ── macOS ──────────────────────────────────────────────────────────────────────
function xmlEscape(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
function installMac() {
  const p = macPlist();
  fs.mkdirSync(path.dirname(p), { recursive: true });
  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>com.claude.discordpresence</string>
  <key>ProgramArguments</key>
  <array>
    <string>${xmlEscape(NODE)}</string>
    <string>${xmlEscape(DAEMON)}</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><false/>
</dict>
</plist>
`;
  fs.writeFileSync(p, plist);
  return new Promise((resolve) => {
    exec(`launchctl unload "${p}" 2>/dev/null; launchctl load "${p}"`, () => resolve(p));
  });
}
function uninstallMac() {
  const p = macPlist();
  return new Promise((resolve) => {
    exec(`launchctl unload "${p}" 2>/dev/null`, () => {
      try { if (fs.existsSync(p)) fs.unlinkSync(p); } catch (_) {}
      resolve(p);
    });
  });
}

// ── Linux ────────────────────────────────────────────────────────────────────
function installLinux() {
  const p = linuxDesktop();
  fs.mkdirSync(path.dirname(p), { recursive: true });
  const desktop = `[Desktop Entry]
Type=Application
Name=Claude Discord Presence
Comment=Show Claude Desktop usage as Discord Rich Presence
Exec="${NODE}" "${DAEMON}"
X-GNOME-Autostart-enabled=true
NoDisplay=true
Terminal=false
`;
  fs.writeFileSync(p, desktop);
  return Promise.resolve(p);
}
function uninstallLinux() {
  const p = linuxDesktop();
  if (fs.existsSync(p)) fs.unlinkSync(p);
  return Promise.resolve(p);
}

// ── Public API ────────────────────────────────────────────────────────────────
function install() {
  if (process.platform === 'win32') return installWindows();
  if (process.platform === 'darwin') return installMac();
  return installLinux();
}
function uninstall() {
  if (process.platform === 'win32') return uninstallWindows();
  if (process.platform === 'darwin') return uninstallMac();
  return uninstallLinux();
}
function isInstalled() {
  if (process.platform === 'win32') return fs.existsSync(windowsStartupVbs());
  if (process.platform === 'darwin') return fs.existsSync(macPlist());
  return fs.existsSync(linuxDesktop());
}
function location() {
  if (process.platform === 'win32') return windowsStartupVbs();
  if (process.platform === 'darwin') return macPlist();
  return linuxDesktop();
}

module.exports = { install, uninstall, isInstalled, location, DAEMON, NODE };
